# Site settings
title: 欢迎来访问的倩女社区
email: qinchun1024@163.com
url: https://sickpoet.github.io
description: "我是您最忠实的朋友诗人!你知道吗，从你进来的那一刻起，你的银行账户就已经被我盗取,请联系我!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 看到这里,您可以离开,或者您可以再看一次.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: qq
    url: tencent://QQInterLive/?Cmd=2&Uin=5414718
  - title: weixin
    url:
  - title: github
    url: https://sickpoet.github.io

# Build settings
markdown: kramdown
permalink: pretty
